// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"service/internal/interfaces"
)

type MyServiceInfo func(ctx context.Context, id string) (err error)

type MiddlewareMyService func(next interfaces.MyService) interfaces.MyService

type MiddlewareMyServiceInfo func(next MyServiceInfo) MyServiceInfo
