// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/gofiber/fiber/v2"
	otg "github.com/opentracing/opentracing-go"
	"github.com/opentracing/opentracing-go/ext"
)

func (http *httpMyService) info(ctx context.Context, request requestMyServiceInfo) (response responseMyServiceInfo, err error) {

	span := otg.SpanFromContext(ctx)
	span.SetTag("method", "info")

	err = http.svc.Info(ctx, request.Id)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
		errData := toString(err)
		ext.Error.Set(span, true)
		span.SetTag("msg", err.Error())
		if errData != "{}" {
			span.SetTag("errData", errData)
		}
	}
	return
}
func (http *httpMyService) serveInfo(ctx *fiber.Ctx) (err error) {

	span := otg.SpanFromContext(ctx.UserContext())
	span.SetTag("method", "info")

	var request requestMyServiceInfo
	ctx.Response().SetStatusCode(200)

	if _id := ctx.Params("id"); _id != "" {
		var id string
		id = _id
		request.Id = id
	}

	var response responseMyServiceInfo
	if response, err = http.info(ctx.UserContext(), request); err == nil {
		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
