// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/opentracing/opentracing-go"
	"service/internal/interfaces"
)

type traceMyService struct {
	next interfaces.MyService
}

func traceMiddlewareMyService(next interfaces.MyService) interfaces.MyService {
	return &traceMyService{next: next}
}

func (svc traceMyService) Info(ctx context.Context, id string) (err error) {
	span := opentracing.SpanFromContext(ctx)
	span.SetTag("method", "Info")
	return svc.next.Info(ctx, id)
}
