// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"fmt"
	"github.com/go-kit/kit/metrics"
	"service/internal/interfaces"
	"time"
)

type metricsMyService struct {
	next            interfaces.MyService
	requestCount    metrics.Counter
	requestCountAll metrics.Counter
	requestLatency  metrics.Histogram
}

func metricsMiddlewareMyService(next interfaces.MyService) interfaces.MyService {
	return &metricsMyService{
		next:            next,
		requestCount:    RequestCount.With("service", "MyService"),
		requestCountAll: RequestCountAll.With("service", "MyService"),
		requestLatency:  RequestLatency.With("service", "MyService"),
	}
}

func (m metricsMyService) Info(ctx context.Context, id string) (err error) {

	defer func(begin time.Time) {
		m.requestLatency.With("method", "info", "success", fmt.Sprint(err == nil)).Observe(time.Since(begin).Seconds())
	}(time.Now())

	defer m.requestCount.With("method", "info", "success", fmt.Sprint(err == nil)).Add(1)

	m.requestCountAll.With("method", "info").Add(1)

	return m.next.Info(ctx, id)
}
