// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

type requestMyServiceInfo struct {
	Id string `json:"id"`
}

// Formal exchange type, please do not delete.
type responseMyServiceInfo struct{}
